project:
  type: website

website:
  title: "Effect of Education on Urban and Rural Populations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Fit.qmd
        text: Model Analysis  
      - text: Further Analysis
        menu: 
          - href: World Regions.qmd
            text: World Regions
          - href: ExpenditureOnEducation.qmd
            text: Development Factors
          - Conclusion.qmd
      - about.qmd
      - Sources.qmd

format:
  html:
    theme: Solarize
    css: styles.css
    toc: true



