project:
  type: website

website:
  title: "Effect of Education on Urban and Rural Populations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: World Regions.qmd
        text: World Regions
      - href: ExpenditureOnEducation.qmd
        text: Development Factors
      - href: Conclusion.qmd
        text: Conclusion
      - about.qmd
      - Sources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



