project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: World Regions.qmd
        text: World Regions
      - href: ExpenditureOnEducation.qmd
        text: Expenditure On Education

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



