---
title: "Development Factors"
execute: 
  echo: false
---

How does government spending on education affect the development of urban and rural areas? On this page we have 3 sets of graphs analyzing the potential effects of a government's education expenditure on 3 developmental factors: Access to Electricity, Safe Drinking Water and Basic Sanitation Services.

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(rstanarm)
library(primer.data)
```

```{r}
#| message: false
#| warning: false
dataset <- read_csv("Data.csv") |>
  as_tibble() |>
  filter(Time > 2014)
```


```{r}
#| message: false
#| warning: false
x <- dataset |>
  mutate(Rural_PopPerc = `Rural population (% of total population) [SP.RUR.TOTL.ZS]`, Urban_PopPerc = `Urban population (% of total population) [SP.URB.TOTL.IN.ZS]`, Rural_PopGrowth = `Rural population growth (annual %) [SP.RUR.TOTL.ZG]`, Urban_PopGrowth = `Urban population growth (annual %) [SP.URB.GROW]`, Educ_Exp_Perc = `Government expenditure on education, total (% of government expenditure) [SE.XPD.TOTL.GB.ZS]`, Country_Name = `Country Name`, Urban_Pop = `Urban population [SP.URB.TOTL]`, Rural_Pop = `Rural population [SP.RUR.TOTL]`, Gross_Exp = `Gross national expenditure (current US$) [NE.DAB.TOTL.CD]`, Elec_Access_Urban = `Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]`, Elec_Access_Rural = `Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]`, Bas_Water_Urban = `People using at least basic drinking water services, urban (% of urban population) [SH.H2O.BASW.UR.ZS]`, Bas_Water_Rural = `People using at least basic drinking water services, rural (% of rural population) [SH.H2O.BASW.RU.ZS]`, Bas_San_Urban = `People using at least basic sanitation services, urban (% of urban population) [SH.STA.BASS.UR.ZS]`, Bas_San_Rural = `People using at least basic sanitation services, rural (% of rural population) [SH.STA.BASS.RU.ZS]`)|>
  select(Time, Country_Name, 
         Educ_Exp_Perc, Gross_Exp,
         Rural_PopPerc, Rural_PopGrowth, 
         Urban_PopPerc, Urban_PopGrowth,
         Urban_Pop, Rural_Pop,
         Elec_Access_Urban, Elec_Access_Rural,
         Bas_Water_Urban, Bas_Water_Rural,
         Bas_San_Urban, Bas_San_Rural)

```


```{r}
#| message: false
#| warning: false
data <- x |> mutate(Educ_Exp_Perc = as.numeric(Educ_Exp_Perc),
            Rural_PopPerc = as.numeric(Rural_PopPerc),
            Rural_PopGrowth = as.numeric(Rural_PopGrowth),
            Urban_PopPerc = as.numeric(Urban_PopPerc),
            Urban_PopGrowth = as.numeric(Urban_PopGrowth),
            Gross_Exp = as.numeric(Gross_Exp),
            Urban_Pop = as.numeric(Urban_Pop),
            Rural_Pop = as.numeric(Rural_Pop),
            Elec_Access_Urban = as.numeric(Elec_Access_Urban),
            Elec_Access_Rural = as.numeric(Elec_Access_Rural), 
            Bas_Water_Urban = as.numeric(Bas_Water_Urban),
            Bas_Water_Rural = as.numeric(Bas_Water_Rural),
            Bas_San_Urban = as.numeric(Bas_San_Urban),
            Bas_San_Rural = as.numeric(Bas_San_Rural)) |>
            drop_na()

```

```{r}
data1 <- data |>
  mutate(Edu_Exp = (Educ_Exp_Perc / 100) * Gross_Exp)
```



```{r}
data1 |>
  mutate(Edu_Exp_Short = Edu_Exp / 100000000000) |>
  filter(Edu_Exp_Short < 1) |>
  ggplot(aes(x = Edu_Exp, y = Elec_Access_Urban)) +
  geom_point(aes(color = Elec_Access_Urban)) +
  geom_smooth(method = "loess", formula = y~x,
              se = FALSE) +
  labs(
    title = "Education Expenditure vs. Percent of Urban Population\nwith Access to Electricity",
    subtitle = "There is a logarithmic positive correlation",
    x = "Government Expenditure on Education($)\n(Billions of dollars)",
    y = "Percent Urban Population\nwith Electricity",
    caption = "Source: WorldBank Dataset"
  ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_continuous(labels = scales::dollar_format(scale = 1/1000000000, suffix = "B")) 
  
```

```{r}
data1 |>
  mutate(Edu_Exp_Short = Edu_Exp / 100000000000) |>
  filter(Edu_Exp_Short < 1) |>
  ggplot(aes(x = Edu_Exp, y = Elec_Access_Rural)) +
  geom_point(aes(color = Elec_Access_Rural)) +
  geom_smooth(method = "loess", formula = y~x,
              se = FALSE) +
  labs(
    title = "Education Expenditure vs. Percent of Rural Population\nwith Access to Electricity",
    subtitle = "There is a logarithmic positive correlation",
    x = "Government Expenditure on Education($)\n(Billions of dollars)",
    y = "Percent Rural Population\nwith Electricity",
    caption = "Source: WorldBank Dataset"
    ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_continuous(labels = scales::dollar_format(scale = 1/1000000000, suffix = "B")) 
```


```{r}
data1 |>
  mutate(Edu_Exp_Short = Edu_Exp / 100000000000) |>
  filter(Edu_Exp_Short < 1) |>
  ggplot(aes(x = Edu_Exp, y = Bas_Water_Urban,
             color = Time)) +
  geom_point() +
  geom_smooth(method = "lm",
              formula = y~x,
              se = FALSE) +
  labs(
    title = "Education Expenditure vs. Percent of Urban Population\nwith Access to Safe Drinking Water",
    subtitle = "There is a clear positive trend",
    x = "Government Expenditure on Education($)\n(Billions of dollars)",
    y = "Percent Urban Population\nwith Safe Drinking Water",
    caption = "Source: WorldBank Dataset"
  ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_continuous(labels = scales::dollar_format(scale = 1/1000000000, suffix = "B")) 
```



```{r}
data1 |>
  mutate(Edu_Exp_Short = Edu_Exp / 100000000000) |>
  filter(Edu_Exp_Short < 1) |>
  ggplot(aes(x = Edu_Exp, y = Bas_Water_Rural,
             color = Time)) +
  geom_point() + 
  geom_smooth(method = "lm",
              formula = y~x,
              se = FALSE) +
  labs(
    title = "Education Expenditure vs. Percent of Rural Population\nwith Access to Safe Drinking Water",
    subtitle = "There is a clear positive trend",
    x = "Government Expenditure on Education($)\n(Billions of dollars)",
    y = "Percent Rural Population\nwith Safe Drinking Water",
    caption = "Source: WorldBank Dataset"
  ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_continuous(labels = scales::dollar_format(scale = 1/1000000000, suffix = "B"))
```


```{r}
data1 |>
  mutate(Edu_Exp_Short = Edu_Exp / 100000000000) |>
  filter(Edu_Exp_Short < 1) |>
  ggplot(aes(x = Edu_Exp, y = Bas_San_Urban,
             alpha = Bas_San_Urban,
             size = Bas_San_Urban)) +
  geom_point() +
  labs(
    title = "Education Expenditure vs. Percent of Urban Population\nwith Access to Sanitation Services",
    subtitle = "There is a clear positive trend",
    x = "Government Expenditure on Education($)\n(Billions of dollars)",
    y = "Percent Urban Population\nwith Basic Sanitation",
    caption = "Source: WorldBank Dataset"
  ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_continuous(labels = scales::dollar_format(scale = 1/1000000000, suffix = "B"))
```


```{r}
data1 |>
  mutate(Edu_Exp_Short = Edu_Exp / 100000000000) |>
  filter(Edu_Exp_Short < 1) |>
  ggplot(aes(x = Edu_Exp, y = Bas_San_Rural,
             alpha = Bas_San_Urban,
             size = Bas_San_Urban)) +
  geom_point() +
  labs(
    title = "Education Expenditure vs. Percent of Rural Population\nwith Access to Sanitation Services",
    subtitle = "There is a clear positive trend",
    x = "Government Expenditure on Education($)\n(Billions of dollars)",
    y = "Percent Rural Population\nwith Basic Sanitation",
    caption = "Source: WorldBank Dataset"
  ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_continuous(labels = scales::dollar_format(scale = 1/1000000000, suffix = "B"))
```

```{r}

#data1 |>
#  mutate(Edu_Exp_Short = Edu_Exp / 100000000000) |>
#  filter(Edu_Exp_Short < 1) |>
#  ggplot(aes(x = Edu_Exp, fill = Time)) +
#  geom_density(alpha = .5) 
```



