---
title: "Model Analysis"
execute: 
  echo: false
---

### Focus Question

How does a government's expenditure on education impact rural and urban population growths?

## Model Definitions

$$y_u = \beta_0  + \beta_1 x_{1,u} + \epsilon_u$$

with $y_u = Urban\_PopGrowth$, $x_1 = edu\_exp$, and $\epsilon_i \sim N(0, \sigma^2)$.


$$y_r = \beta_0  + \beta_1 x_{1,r} + \epsilon_r$$
with $y_u = Rural\_PopGrowth$, $x_1 = edu\_exp$, and $\epsilon_r \sim N(0, \sigma^2)$.

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(rstanarm)
library(primer.data)
```

```{r}
#| message: false
#| warning: false
dataset <- read_csv("Data.csv") |>
  as_tibble() |>
  filter(Time > 2010 & Time < 2021)
```

```{r}
#| message: false
#| warning: false
x <- dataset |>
  mutate(Rural_PopPerc = `Rural population (% of total population) [SP.RUR.TOTL.ZS]`, Urban_PopPerc = `Urban population (% of total population) [SP.URB.TOTL.IN.ZS]`, Rural_PopGrowth = `Rural population growth (annual %) [SP.RUR.TOTL.ZG]`, Urban_PopGrowth = `Urban population growth (annual %) [SP.URB.GROW]`, Educ_Exp_Perc = `Government expenditure on education, total (% of government expenditure) [SE.XPD.TOTL.GB.ZS]`, Country_Name = `Country Name`, Urban_Pop = `Urban population [SP.URB.TOTL]`, Rural_Pop = `Rural population [SP.RUR.TOTL]`, Gross_Exp = `Gross national expenditure (current US$) [NE.DAB.TOTL.CD]`, Elec_Access_Urban = `Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]`, Elec_Access_Rural = `Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]`, Bas_Water_Urban = `People using at least basic drinking water services, urban (% of urban population) [SH.H2O.BASW.UR.ZS]`, Bas_Water_Rural = `People using at least basic drinking water services, rural (% of rural population) [SH.H2O.BASW.RU.ZS]`, Bas_San_Urban = `People using at least basic sanitation services, urban (% of urban population) [SH.STA.BASS.UR.ZS]`, Bas_San_Rural = `People using at least basic sanitation services, rural (% of rural population) [SH.STA.BASS.RU.ZS]`)|>
  select(Time, Country_Name, 
         Educ_Exp_Perc, Gross_Exp,
         Rural_PopPerc, Rural_PopGrowth, 
         Urban_PopPerc, Urban_PopGrowth,
         Urban_Pop, Rural_Pop,
         Elec_Access_Urban, Elec_Access_Rural,
         Bas_Water_Urban, Bas_Water_Rural,
         Bas_San_Urban, Bas_San_Rural)
```

```{r}
#| message: false
#| warning: false
data <- x |> mutate(Educ_Exp_Perc = as.numeric(Educ_Exp_Perc),
            Rural_PopPerc = as.numeric(Rural_PopPerc),
            Rural_PopGrowth = as.numeric(Rural_PopGrowth),
            Urban_PopPerc = as.numeric(Urban_PopPerc),
            Urban_PopGrowth = as.numeric(Urban_PopGrowth),
            Gross_Exp = as.numeric(Gross_Exp),
            Urban_Pop = as.numeric(Urban_Pop),
            Rural_Pop = as.numeric(Rural_Pop),
            Elec_Access_Urban = as.numeric(Elec_Access_Urban),
            Elec_Access_Rural = as.numeric(Elec_Access_Rural), 
            Bas_Water_Urban = as.numeric(Bas_Water_Urban),
            Bas_Water_Rural = as.numeric(Bas_Water_Rural),
            Bas_San_Urban = as.numeric(Bas_San_Urban),
            Bas_San_Rural = as.numeric(Bas_San_Rural)) |>
            drop_na()

```


```{r}
data1 <- data |>
  mutate(Edu_Exp = (Educ_Exp_Perc / 100) * Gross_Exp)

```



```{r}
#| message: false
#| warning: false

data2 <- data1 |>
  mutate(Edu_Exp_Short = Edu_Exp / 100000000000)

fit_obj1 <- stan_glm(data = data2,
            formula = Edu_Exp ~ Urban_PopGrowth,
            family = gaussian,
            refresh = 0,
            seed = 42)
fit_obj1
  

```


```{r}
#| message: false
#| warning: false
fit_obj1 |>
  as_tibble() |>
rename(mu = `(Intercept)`) |>
ggplot(aes(x = mu)) +
geom_histogram(aes(y = after_stat(count / sum(count)))) +
  labs(
    title = "Posterior Distribution of Education Expenditure on Urban Population Growth",
    subtitle = "Every 440 billion dollars spent on educations correlates\nwith about .1% Annual Urban Population Growth",
    x = "Government Expenditure on Education($)\n(Billions of dollars)",
    y = "Percent Urban Population Growth",
    caption = "Source: WorldBank Dataset") +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_continuous(labels = scales::dollar_format(scale = 1/1000000000, suffix = "B")) +
  theme_classic()
```

```{r}
#| message: false
#| warning: false
data2 <- data1 |>
  mutate(Edu_Exp_Short = Edu_Exp / 100000000000)

fit_obj2 <- stan_glm(data = data2,
            formula = Edu_Exp ~ Rural_PopGrowth,
            family = gaussian,
            refresh = 0,
            seed = 42)
fit_obj2
```

```{r}
#| message: false
#| warning: false
fit_obj2 |>
  as_tibble() |>
rename(mu = `(Intercept)`) |>
ggplot(aes(x = mu)) +
geom_histogram(aes(y = after_stat(count / sum(count)))) +
  labs(
    title = "Posterior Distribution of Education Expenditure on Rural Population Growth",
    subtitle = "Every 350 billion dollars spent on educations correlates\nwith about .08% Annual Rural Population Growth",
    x = "Government Expenditure on Education($)\n(Billions of dollars)",
    y = "Percent Rural Population Growth",
    caption = "Source: WorldBank Dataset") +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_continuous(labels = scales::dollar_format(scale = 1/1000000000, suffix = "B")) +
  theme_classic()
```

